export const services = [
  {
    serviceLabel: "Web Development",
    services: [
      "Custom Web Applications",
      "Website Redesign",
      "E-Commerce Website Development",
      "Web Support and Maintenance ",
      "Full Stack Web Development",
      "QA & Testing",
      "Software Project Rescue",
      "Co-development",
      "Integration of 3rd party services",
      "Payment Gateway Integration",
    ],
  },
  {
    serviceLabel: "Backend Development",
    services: [
      "Create development solutions for code-related problems",
      "Optimize and maintain existing code",
      "Create database solutions for data-related problems",
      "Integrate and maintain 3rd party services",
      "Create API solutions for data-related problems",
      "Identify and resolve performance issues",
      "Communicate effectively with the team",
      "Create and maintain documentation",
      "Organize and manage code",
      "Debug and troubleshoot code",
    ],
  },
  {
    serviceLabel: "Quality Assurance",
    services: [
      "Quality Control",
      "Manual & Automated Testing",
      "Quality consulting",
      "Technical support / maintenance",
      "Mobile & Web Testing",
      "Performance Testing",
      "Security Testing",
      "Bug Testing",
      "Build a Test Plan",
      "Integrating Testing Tools",
    ],
  },
];
