export const services = [
  {
    serviceLabel: "Web Development",
    services: [
      "Custom Web Applications",
      "Website Redesign",
      "E-Commerce Website Development",
      "Web Support and Maintenance ",
      "Full Stack Web Development",
      "QA & Testing",
      "Software Project Rescue",
      "Co-development",
      "Integration of 3rd party services",
      "Payment Gateway Integration",
    ],
  },
  {
    serviceLabel: "Content Creation",
    services: [
      "Lorem, ipsum dolor sit amet consectetur elit.",
      "Lorem, ipsum dolor sit amet consectetur elit.",
      "Lorem, ipsum dolor sit amet consectetur elit.",
      "Lorem, ipsum dolor sit amet consectetur elit.",
      "Lorem, ipsum dolor sit amet consectetur elit.",
      "Lorem, ipsum dolor sit amet consectetur elit.",
      "Lorem, ipsum dolor sit amet consectetur elit.",
      "Lorem, ipsum dolor sit amet consectetur elit.",
    ],
  },
  {
    serviceLabel: "Quality Assurance",
    services: [
      "Quality Control",
      "Manual & Automated Testing",
      "Quality consulting",
      "Technical support / maintenance",
      "Mobile & Web Testing",
      "Performance Testing",
      "Security Testing",
      "Bug Testing",
      "Build a Test Plan",
      "Integrating Testing Tools",
    ],
  },
];
